version: '3.8'

services:
  backend:
    image: backend
    container_name: backend
    build:
        context: ./be
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - maria_db
  frontend:
    image: frontend
    container_name: frontend
    build:
        context: ./fe
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
  maria_db:
    image: "mariadb:latest"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mariadb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password