spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mariadb?useSSL=false&serverTimezone=UTC
    username: user
    password: password
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

