spring:
  datasource:
    url: jdbc:mariadb://maria_db:3306/mariadb
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
        show-details: always